name: 'Build & Test'
on:
    workflow_call:
defaults:
    run:
        shell: bash
permissions:
    contents: write
    packages: read
    checks: write

jobs:
    build:
        name: 'Build Node.js'
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - uses: pnpm/action-setup@v3
              with:
                version: 8

            - uses: actions/setup-node@v4
              with:
                node-version: 18
                cache: "pnpm"

            - name: "Clean install dependencies"
              run: pnpm install --no-frozen-lockfile

            - name: "Run npm build"
              run: pnpm build

    test:
        name: 'Test Node.js'
        runs-on: ubuntu-latest

        needs: build

        steps:
            - uses: actions/checkout@v4

            - uses: pnpm/action-setup@v3
              with:
                version: 8

            - uses: actions/setup-node@v4
              with:
                node-version: 18
                cache: "pnpm"

            - name: "Clean install dependencies"
              run: pnpm install --no-frozen-lockfile

            - name: "Run npm build"
              run: pnpm build

            - name: 'Run pnpm test'
              run: pnpm test
