name: 'Release'
on:
    workflow_call:
defaults:
    run:
        shell: bash
permissions:
    contents: write
    packages: write
env:
    CI: true

jobs:
    release:
        name: 'Semantic Release'
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
                  persist-credentials: false

            - uses: pnpm/action-setup@v2
              with:
                  version: 8

            - uses: actions/setup-node@v4
              with:
                  # Semantic release needs at lease Node 18
                  node-version: 18
                  cache: 'pnpm'

            - name: 'Obtain Github App token'
              id: app-token
              uses: getsentry/action-github-app-token@v2.0.0
              with:
                  app_id: ${{ secrets.BOT_APP_ID }}
                  private_key: ${{ secrets.BOT_APP_PRIVATE_KEY }}

            - name: 'Clean install dependencies'
              run: pnpm install --no-frozen-lockfile

            - name: 'Run pnpm build'
              run: pnpm build

            - name: 'Execute Semantic Release'
              run: pnpm release
              env:
                  GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
